### PR TITLE
Fix max_nb_chars parameter when adding paragraphs

### PR DESCRIPTION
**Pull request by martinburchell**
Hello. Thanks for making faker-file. I've just added it to https://github.com/ucam-department-of-psychiatry/crate/

Looking through the source code I spotted what looks like a copy-paste error when retrieving the value of `max_nb_chars` in various functions. I've not tested it as it looked like quite a simple change and I had problems setting up the development environment. I'm assuming your CI will pick up any problems!

### CODE REVIEW

**Review by barseghyanartur — APPROVED** [review]
Thanks!

**Comment by barseghyanartur** [comment]
@martinburchell:

> ...I had problems setting up the development environment...

Could you, please, provide more details on that?

**Comment by martinburchell** [comment]
> @martinburchell:
> 
> > ...I had problems setting up the development environment...
> 
> Could you, please, provide more details on that?

Yes I've realised later that in order to run the tests I needed to install a bunch of things from `examples/requirements`. Now the tests run but I get 23 errors along the lines of :
```
E           OSError: wkhtmltoimage reported an error:
E           Loading page (1/2)
Rendering (2/2)                                                          ] 0%
Error: Could not save image                                              ] 0%
Done                                                               ======] 100%
E           Exit with code 1, due to unknown error.

../../.virtualenvs/faker-file/lib/python3.9/site-packages/imgkit/imgkit.py:257: OSError
```
 
I'm using Python 3.9 and I note that Python 3.9 is not enabled for everything in `.github/workflows/test.yml` so maybe that's expected.

**Comment by barseghyanartur** [comment]
@martinburchell 

Thanks for sharing! 

It's a bit more complex than that. The `tox` library is used for the matrix, and although `GitHub Actions` are capable of doing that too, you can't run that locally for testing. At the time of writing this a couple of years ago, I considered that important (lazy to change it now, because it works).

The main tests should (and do) pass for Python 3.9 that as well.

Thus, it shouldn't happen, but since it's dependent on a third-party system library (`wkhtmltopdf`), it's not entirely bizarre it happens. Perhaps the best way to fix that is to update the outdated Dockerfile that does nothing ATM, to include all required system deps and run local tests in Docker only. Will do when have some spare time.

**Comment by barseghyanartur** [comment]
@martinburchell 

Version 0.17.14 contains changes of this PR.

**Pull request merged**
